version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.1
    steps:
      - checkout
      - run:
          name: install dependencies
          command: pip install -r requirements.txt
      - run:
          name: create migrations
          command: python manage.py migrate
      - run:
          name: run tests
          command: python3 manage.py test

workflows:
  build-and-test-workflow:
    jobs:
      - build-and-test

